name: Deploy develop release APK

on:
  push:
    branches:
      - develop

jobs:
  deploy-develop-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and Sign APK
        uses: ./.github/actions/build-release-apk
        with:
          android-keystore-base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          android-key-alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          android-key-alias-password: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
          base-url: ${{ secrets.BASE_URL }}

      - name: Deploy to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: ${{ env.SIGNED_APK_PATH }}
          debug: true
          groups: testers-develop

      - name: Publish APK to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: develop-v${{ env.APK_VERSION }}-attempt${{ github.run_attempt }}
          name: Develop APK v${{ env.APK_VERSION }}
          files: ${{ env.SIGNED_APK_PATH }}
          prerelease: true
          generate_release_notes: true

